version: '3'

services:
    base:
        container_name: python_dev
        image: python:3
        volumes:
            - ~/base/space/gh:/opt/base
        ports:
            - 8080:8080
        command: ['python3', '-m', 'http.server', '8080']
        networks: 
            - dev
    ubuntu:
        container_name: ubuntu_dev
        image: ubuntu:latest
        volumes:
            - ~/base/space/gh:/opt/base
        networks: 
            - dev
        # ports:
        #     - 8081:8080
        # command: ['python3', '-m', 'http.server', '8080']        

networks:
    dev:
        driver: bridge