version: '3'

services:
    base:
        container_name: python_dev
        image: python:3
        volumes:
            - ~/base/space/gh:/opt/base
        ports:
            - 8080:8080
        command: ['python3', '-m', 'http.server', '8080']
