version: '3'

services:
    python:
        container_name: python
        image: python:2
        volumes:
            - ~/base/space/:/opt/base
        networks: 
            - dev
        stdin_open: true
        tty: true
    jupyter:
        container_name: jupyter
        image: jupyter/minimal-notebook
        volumes:
            - ~/base/space/:/home/jovyan/workspace
        ports:
            - 8888:8888
        networks:
            - dev
    ubuntu:
        container_name: ubuntu
        image: ubuntu:latest
        volumes:
            - ~/base/space/:/opt/base
        networks: 
            - dev
        stdin_open: true
        tty: true
    golang:
        container_name: golang
        image: golang:latest
        volumes:
            - ~/base/space/:/opt/base
        networks:
            - dev
        stdin_open: true
        tty: true

networks:
    dev:
        driver: bridge