version: "3"

services:
  app:
    container_name: dev_python
    build:
        context: .
        dockerfile: python-dockerfile
    image: ubuntu:latest    # image
    # build: ../
    # stdin_open: true        # docker run -i
    # tty: true               # docker run -t
    # ports:                  # port mapping
    #     - "8080:80"
    volumes:                # volume mappings
        - ~/base/:/opt/base/
    working_dir: /opt/base/ # change working directory
    # entrypoint: ["/bin/bash", "-c"]
    # command: 
    #     - /bin/bash
    #     - -c
    #     - |
    #         yes | apt-get install net-tools
    #         yes | apt-get install vim